NUMINSTR = 5
I_PUSH, I_ADD, I_CREATEPAGE, I_CALL, I_COPYKEY = range(NUMINSTR)

INSTRUCTIONNAMES = "I_PUSH, I_ADD, I_CREATEPAGE, I_CALL, I_COPYKEY".split(", ")

R_CARGS, R_NONE = range(2)
# Codeargs
REQUIREMENTS = {
    I_PUSH: [1],
    I_ADD: [0]
}
